Task-39984: Improve keyword set for DLP
Meeds-io/commons pull request #120
Opened 2021-02-22 15:41 UTC by AzmiTouil

Add the ability to add more than one word (at least two words) in the DLP keyword edition.

2021-02-22 16:13 UTC, rdenarie requested changes

2021-02-22 16:13 UTC, rdenarie commented on commons-search/src/main/java/org/exoplatform/commons/search/es/ElasticSearchServiceConnector.java
> +          esQuery.append("                    \"boost\" : 5,\n");
why do you add a boost here ?

2021-02-22 16:40 UTC, AzmiTouil commented on commons-search/src/main/java/org/exoplatform/commons/search/es/ElasticSearchServiceConnector.java
> +          esQuery.append("                    \"boost\" : 5,\n");
no needed , removed!

2021-02-22 16:51 UTC, rdenarie approved these changes, later dismissed

2021-02-24 08:08 UTC, rdenarie approved these changes

2021-02-24 14:31 UTC, merged