Task-37622: Implement Dlp feature V0
Meeds-io/commons pull request #48
Opened 2020-12-15 11:26 UTC by azayati

2020-12-15 11:43 UTC, rdenarie requested changes
We should add unit tests

2020-12-15 11:43 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/processor/impl/DlpOperationProcessorImpl.java
> +    dlpOperationDAO.deleteAllDlpOperationsHavingIdLessThanOrEqual(maxDlpOperationId);
I'm not sure to understand what we delete here. Can you explain ?

2020-12-15 11:43 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/processor/impl/DlpOperationProcessorImpl.java
> +    }
Can you explain what this for does ?

2020-12-16 07:49 UTC, rdenarie requested changes

2020-12-16 07:49 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/dao/DlpOperationDAO.java
> +  void deleteAllDlpOperationsHavingIdLessThanOrEqual(long id);
To remove I think

2020-12-16 07:49 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/dao/impl/DlpOperationDAOImpl.java
> +  }
to remove

2020-12-16 07:49 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/domain/DlpOperation.java
> +        query = "DELETE FROM DlpOperation q WHERE q.id <= :id"),
To remove

2020-12-16 07:49 UTC, rdenarie commented on commons-dlp/src/main/resources/conf/portal/configuration.xml
> +  </external-component-plugins>
CronJob or PeriodJob ?

With a cronJob, we can say to Quartz to not start a new execution if the first one is not finished

In addition, I thinkg that execution time each 1 minute is sufficient

2020-12-16 08:00 UTC, azayati commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/domain/DlpOperation.java
> +        query = "DELETE FROM DlpOperation q WHERE q.id <= :id"),
removed

2020-12-16 08:00 UTC, azayati commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/dao/impl/DlpOperationDAOImpl.java
> +  }
removed

2020-12-16 08:13 UTC, azayati commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/dao/DlpOperationDAO.java
> +  void deleteAllDlpOperationsHavingIdLessThanOrEqual(long id);
removed

2020-12-16 12:55 UTC, rdenarie requested changes

2020-12-16 12:55 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/connector/DlpServiceConnector.java
> +  protected static final String DLP_POSITIVE_DETECTION = "dlpPositiveDetection ";
```suggestion
  protected static final String DLP_POSITIVE_DETECTION = "dlpPositiveDetection";
```

2020-12-16 12:55 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/connector/DlpServiceConnector.java
> +  protected static final String DLP_FEATURE = "dlp";
to be removed

2020-12-16 13:04 UTC, azayati commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/connector/DlpServiceConnector.java
> +  protected static final String DLP_POSITIVE_DETECTION = "dlpPositiveDetection ";
done

2020-12-16 13:04 UTC, azayati commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/connector/DlpServiceConnector.java
> +  protected static final String DLP_FEATURE = "dlp";
done

2020-12-16 13:12 UTC, rdenarie approved these changes

2020-12-16 15:20 UTC, merged