Task-37845 : Active DLP document preview
Meeds-io/commons pull request #75
Opened 2021-01-19 23:00 UTC by ahmadmido

2021-01-20 08:34 UTC, plamarque submitted a review, later dismissed
typo on "reference"

2021-01-20 08:34 UTC, plamarque commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/dto/DlpPositiveItem.java
> +    public void setRefernece(String refernece) { this.refernece = refernece; }
```suggestion
    public void setReference(String reference) { this.reference = reference; }
```

2021-01-20 08:34 UTC, plamarque commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/dto/DlpPositiveItem.java
> +    public String getRefernece() { return refernece; }
```suggestion
    public String getReference() { return reference; }
```

2021-01-20 08:34 UTC, plamarque commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/dto/DlpPositiveItem.java
> +    private String refernece;
```suggestion
    private String reference;
```

2021-01-20 14:30 UTC, rdenarie submitted a review, later dismissed

2021-01-25 10:50 UTC, rdenarie requested changes

2021-01-25 10:50 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/domain/DlpPositiveItemEntity.java
> +    @Column(name = "ITEM_DOWNLOAD_URL")
In fact, I think we should not store that, for 2 reasons :
1) If DLPPositiveItem is related to an activity, or a wiki or something different from a document, we will not have a "download" url
2) This url can be computed at display with the item reference. If the document is moved in Security folder from the moment it is put in quarantine and the moment it is previewed, the url can change. By computing it at display, we ensure that the url is still ok

2021-01-25 10:50 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/rest/DlpItemRestServices.java
> +    @ApiOperation(value = "Retrieves the url of dlp positive items", httpMethod = "GET", response = Response.class, produces = "application/json",
Why do we need a specific rest service only for url ?
Is it not possible to get it when getting the item list ?

2021-01-26 09:10 UTC, rdenarie approved these changes

2021-01-26 10:09 UTC, merged