Task-37846 : Active DLP restore action
Meeds-io/commons pull request #78
Opened 2021-01-21 20:41 UTC by ahmadmido

2021-01-22 15:02 UTC, rdenarie submitted a review, later dismissed

2021-01-25 08:16 UTC, rdenarie requested changes

2021-01-25 08:16 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/service/impl/DlpPositiveItemServiceImpl.java
> +import java.awt.*;
Why do you need awt dependency ?

2021-01-26 09:13 UTC, rdenarie requested changes

2021-01-26 09:13 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/service/impl/DlpPositiveItemServiceImpl.java
> +        listenerService.broadcast(new Event("dlp.listener.event.move.document", null, dlpPositiveItemEntity.getReference()));
```suggestion
        listenerService.broadcast(new Event("dlp.listener.event.restore.item", null, dlpPositiveItemEntity.getReference()));
```
I think we should rename the event

2021-01-26 09:45 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/service/impl/DlpPositiveItemServiceImpl.java
> +        listenerService.broadcast(new Event("dlp.listener.event.delete.item", null, dlpPositiveItemEntity.getReference()));
did you change also in configuration ?

2021-01-26 09:47 UTC, ahmadmido commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/service/impl/DlpPositiveItemServiceImpl.java
> +        listenerService.broadcast(new Event("dlp.listener.event.delete.item", null, dlpPositiveItemEntity.getReference()));
yes in ECMS

2021-01-27 08:06 UTC, rdenarie requested changes

2021-01-27 08:06 UTC, rdenarie commented on commons-dlp/src/main/java/org/exoplatform/commons/dlp/service/impl/RestoredDlpItemServiceImpl.java
> +  public List<RestoredDlpItem> getRestoredDlpItems(int offset, int limit) throws Exception {
Why this one is necessary ? In which case should we get a list of RestoreDlpItems ?

2021-01-27 08:06 UTC, rdenarie commented on commons-dlp/src/main/resources/db/changelog/exo-dlp.db.changelog-1.0.0.xml
> +    <createSequence sequenceName="SEQ_RESTORED_DLP_ITEMS_ID" startValue="1"/>
the createSequence should be inside another changetset, applicable only for psql

2021-01-27 14:55 UTC, rdenarie approved these changes, later dismissed

2021-01-28 14:32 UTC, rdenarie approved these changes, later dismissed

2021-02-02 10:16 UTC, rdenarie approved these changes

2021-02-02 10:16 UTC, merged